### ISSUE TITLE
Statically resolve nix-prefetch-git

### ISSUE THREAD

**Issue by ryantrinkle** [obsidiansystems/nix-thunk#9]
Running nix-thunk on a system that does not have nix-prefetch-git available in the environment results in:
```
nix-thunk: nix-prefetch-git: createProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
```
Instead, we should use `staticWhich` or similar to ensure it's always available.

**Comment by madeline-os** [comment]
Done as of 0.5.1.0
